#!/bin/sh

PATH='/sbin:/bin'
basedir="/sys/class/gpio"
devpath=$1

if [ "$1" = "enable" ] ; then
    for f in export unexport ; do
        chmod g+w $basedir/$f
        chown :gpio $basedir/$f
    done
else
    for f in active_low direction edge value ; do
        chmod g+w /sys${devpath}/$f
        chown :gpio /sys${devpath}/$f
    done
fi
exit 0