oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase > Class Template Reference
#include <KalmanIMU.h>
Public Types
typedef StateKalmanIMU< T > S
typedef OrientationMeasurementKalmanIMU< T > M
Public Member Functions
OrientationMeasurementModelKalmanIMU ()
M h (const S &x) const
Detailed Description
template<typename T, template< class > class CovarianceBase = Kalman::StandardBase>
class oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >
Definition at line 157 of file KalmanIMU.h.
Member Typedef Documentation
M
template<typename T , template< class > class CovarianceBase = Kalman::StandardBase>
typedef OrientationMeasurementKalmanIMU<T> oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::M
Definition at line 162 of file KalmanIMU.h.
S
template<typename T , template< class > class CovarianceBase = Kalman::StandardBase>
typedef StateKalmanIMU<T> oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::S
Definition at line 160 of file KalmanIMU.h.
Constructor & Destructor Documentation
OrientationMeasurementModelKalmanIMU()
template<typename T , template< class > class CovarianceBase = Kalman::StandardBase>
oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::OrientationMeasurementModelKalmanIMU () [inline]
Definition at line 164 of file KalmanIMU.h.
Member Function Documentation
h()
template<typename T , template< class > class CovarianceBase = Kalman::StandardBase>
M oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::h (const S & x) const [inline]
Definition at line 169 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::phi(), oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::phi(), oCpt::components::sensors::StateKalmanIMU< T >::phiPrime(), oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::phiPrime(), oCpt::components::sensors::StateKalmanIMU< T >::psi(), oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::psi(), oCpt::components::sensors::StateKalmanIMU< T >::psiPrime(), oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::psiPrime(), oCpt::components::sensors::StateKalmanIMU< T >::theta(), oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::theta(), oCpt::components::sensors::StateKalmanIMU< T >::thetaPrime(), and oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::thetaPrime().
The documentation for this class was generated from the following file:
/projects/mti/ohCaptain/ohCaptain/include/Sensors/KalmanIMU.h