oCpt::protocol::Serial Class Reference
#include <Controller.h>
Public Types
typedef boost::shared_ptr< Serial > ptr
typedef std::function< void(const unsigned char *, size_t)> cb_func
typedef boost::asio::serial_port_base::parity parity_t
typedef boost::asio::serial_port_base::character_size character_size_t
typedef boost::asio::serial_port_base::flow_control flow_control_t
typedef boost::asio::serial_port_base::stop_bits stop_bits_t
typedef boost::shared_ptr< boost::asio::io_service > io_service_t
typedef boost::asio::serial_port serialport_t
typedef boost::signals2::signal< void()> signal_t
Public Member Functions
Serial (const std::string &device, unsigned int baudrate, io_service_t ioservice=io_service_t(new boost::asio::io_service()), parity_t parity=parity_t(parity_t::none), character_size_t csize=character_size_t(8), flow_control_t flow=flow_control_t(flow_control_t::none), stop_bits_t stop=stop_bits_t(stop_bits_t::one), unsigned int maxreadlentgh=4096)
void open ()
void start ()
bool isOpen ()
void close ()
bool write (const std::string &msg)
bool write (const std::vector< unsigned char > &data)
void setReadCallback (cb_func cb_function)
void setIOservice (boost::shared_ptr< boost::asio::io_service > io_ptr)
std::deque< std::string > * getReturnMsgQueue ()
std::string readFiFoMsg ()
void setMaxReadLength (unsigned int maxReadLength)
Public Attributes
signal_t msgRecievedSig
Protected Member Functions
void internalCallback (const unsigned char *data, size_t size)
void closeCallback (const boost::system::error_code &error)
void readComplete (const boost::system::error_code &error, size_t bytes_transferred)
void writeCallback (const std::vector< unsigned char > &msg)
void writeStart ()
void writeComplete (const boost::system::error_code &error)
void ReadStart ()
Protected Attributes
unsigned int maxReadLength_
std::deque< std::vector< unsigned char > > msgQueue_
std::deque< std::string > returnMsgQueue_
std::string msg_
std::string receivedMsg_
unsigned char read_msg [4096]
cb_func callback_
io_service_t ioservice_
std::string device_
unsigned int baudrate_
parity_t parity_
character_size_t csize_
flow_control_t flow_
stop_bits_t stop_
serialport_t serialport_
bool firstMsg = true
Detailed Description
Communication via the serial port, using an Asynchrounous Input Output setup, provided by Boost. All communication is handled on the background via a io_service. When data is recieved a callback function is called. This can either be an external function or an internal one, which sends a signal for each new line. The lines can then be read using a FiFo function.
Definition at line 390 of file Controller.h.
Member Typedef Documentation
cb_func
typedef std::function<void(const unsigned char *, size_t)> oCpt::protocol::Serial::cb_func
Definition at line 394 of file Controller.h.
character_size_t
typedef boost::asio::serial_port_base::character_size oCpt::protocol::Serial::character_size_t
Definition at line 396 of file Controller.h.
flow_control_t
typedef boost::asio::serial_port_base::flow_control oCpt::protocol::Serial::flow_control_t
Definition at line 397 of file Controller.h.
io_service_t
typedef boost::shared_ptr<boost::asio::io_service> oCpt::protocol::Serial::io_service_t
Definition at line 399 of file Controller.h.
parity_t
typedef boost::asio::serial_port_base::parity oCpt::protocol::Serial::parity_t
Definition at line 395 of file Controller.h.
ptr
typedef boost::shared_ptr<Serial> oCpt::protocol::Serial::ptr
Definition at line 392 of file Controller.h.
serialport_t
typedef boost::asio::serial_port oCpt::protocol::Serial::serialport_t
Definition at line 400 of file Controller.h.
signal_t
typedef boost::signals2::signal<void()> oCpt::protocol::Serial::signal_t
Definition at line 401 of file Controller.h.
stop_bits_t
typedef boost::asio::serial_port_base::stop_bits oCpt::protocol::Serial::stop_bits_t
Definition at line 398 of file Controller.h.
Constructor & Destructor Documentation
Serial()
oCpt::protocol::Serial::Serial (const std::string & device, unsigned int baudrate, io_service_t ioservice = io_service_t(new boost::asio::io_service()), Serial::parity_t parity = parity_t(parity_t::none), Serial::character_size_t csize = character_size_t(8), Serial::flow_control_t flow = flow_control_t(flow_control_t::none), Serial::stop_bits_t stop = stop_bits_t(stop_bits_t::one), unsigned int maxreadlentgh = 4096)
Constructor of the Serial class
Parameters
device a string representing the device path eq. /dev/tty0
baudrate the baudrate of the device eq. 9600, 57600, 115200
ioservice the io service to be used standard it's a new service
parity the parity of the Serial port with a standard parity of Parity_t::none
csize The character_size with a standard value of 8
flow The flow control of thye device with a standard value of flow_control_t::none
stop The stop bit of the device with a standard value of stop_bits_t::none
maxreadlentgh the Maximum buffer with a standard value of 4096
Definition at line 99 of file Controller.cpp.
References callback_, and internalCallback().
Member Function Documentation
close()
void oCpt::protocol::Serial::close ()
Closes the port when it is open
Definition at line 142 of file Controller.cpp.
References closeCallback(), ioservice_, and serialport_.
closeCallback()
void oCpt::protocol::Serial::closeCallback (const boost::system::error_code & error) [protected]
The callback function which is called after the port is closed
Parameters
error an past trhough boost::system::error_code
Definition at line 159 of file Controller.cpp.
References serialport_.
Referenced by close(), readComplete(), and writeComplete().
getReturnMsgQueue()
std::deque< std::string > * oCpt::protocol::Serial::getReturnMsgQueue ()
Get the complete returnMsg que
Returns
a deque with all the return lines
Definition at line 197 of file Controller.cpp.
References returnMsgQueue_.
internalCallback()
void oCpt::protocol::Serial::internalCallback (const unsigned char * data, size_t size) [protected]
The internal callback function, which handles messages longer then maxreadlentgh and splits the message with
Parameters
data the buffer obtained by the serial port
size the size obtained
Definition at line 208 of file Controller.cpp.
References msgRecievedSig, receivedMsg_, and returnMsgQueue_.
Referenced by Serial().
isOpen()
bool oCpt::protocol::Serial::isOpen ()
Checks if the port is open
Returns
either true or false
Definition at line 138 of file Controller.cpp.
References serialport_.
Referenced by open(), ReadStart(), start(), and write().
open()
void oCpt::protocol::Serial::open ()
Open teh serial port
Definition at line 118 of file Controller.cpp.
References baudrate_, csize_, device_, flow_, ioservice_, isOpen(), parity_, serialport_, and stop_.
Referenced by oCpt::LoRa::initialize().
readComplete()
void oCpt::protocol::Serial::readComplete (const boost::system::error_code & error, size_t bytes_transferred) [protected]
The callbackfunction to be performed when reading is complete
Parameters
error boost::system::error_code if an error is presented
bytes_transferred number of bytes that are transfered
Definition at line 188 of file Controller.cpp.
References callback_, closeCallback(), read_msg, and ReadStart().
Referenced by ReadStart().
readFiFoMsg()
std::string oCpt::protocol::Serial::readFiFoMsg ()
Gets the first recieved message, which is then removed from the queue
Returns
Definition at line 201 of file Controller.cpp.
References returnMsgQueue_.
Referenced by oCpt::LoRa::messageRecieved().
ReadStart()
void oCpt::protocol::Serial::ReadStart () [protected]
Start the reading process
Definition at line 178 of file Controller.cpp.
References isOpen(), maxReadLength_, read_msg, readComplete(), and serialport_.
Referenced by readComplete(), and start().
setIOservice()
void oCpt::protocol::Serial::setIOservice (boost::shared_ptr< boost::asio::io_service > io_ptr)
set a new IO service
Parameters
io_ptr a shared_ptr to the new IO service
Definition at line 155 of file Controller.cpp.
References ioservice_.
setMaxReadLength()
void oCpt::protocol::Serial::setMaxReadLength (unsigned int maxReadLength)
Set the maximum buffer of the Serial class
Parameters
maxReadLength the number of bytes
Definition at line 287 of file Controller.cpp.
References maxReadLength_.
setReadCallback()
void oCpt::protocol::Serial::setReadCallback (cb_func cb_function)
Set a new callback function
Parameters
cb_function the callback function
Definition at line 151 of file Controller.cpp.
References callback_.
start()
void oCpt::protocol::Serial::start ()
Start the io_service on a sepearte thread
Definition at line 166 of file Controller.cpp.
References ioservice_, isOpen(), and ReadStart().
Referenced by oCpt::LoRa::initialize().
write() [1/2]
bool oCpt::protocol::Serial::write (const std::string & msg)
Write a message to the port
Parameters
msg a string with the payload
Returns
either true or false depending if writting was sucsesfull or not
Definition at line 238 of file Controller.cpp.
Referenced by oCpt::LoRa::macpause(), oCpt::LoRa::rx(), oCpt::LoRa::sendMessage(), and oCpt::LoRa::write().
write() [2/2]
bool oCpt::protocol::Serial::write (const std::vector< unsigned char > & data)
Write a message as a vector of unsigned chars
Parameters
data the message to be send
Returns
either true or false depending if writting was sucsesfull or not
Definition at line 244 of file Controller.cpp.
References ioservice_, isOpen(), and writeCallback().
writeCallback()
void oCpt::protocol::Serial::writeCallback (const std::vector< unsigned char > & msg) [protected]
When the writing is finished call this function, which will write the next message if present
Parameters
msg the message to write as an vector of unsigned char
Definition at line 256 of file Controller.cpp.
References msgQueue_, and writeStart().
Referenced by write().
writeComplete()
void oCpt::protocol::Serial::writeComplete (const boost::system::error_code & error) [protected]
restart the write process when the previous write is finished
Parameters
error
Definition at line 275 of file Controller.cpp.
References closeCallback(), msgQueue_, and writeStart().
Referenced by writeStart().
writeStart()
void oCpt::protocol::Serial::writeStart () [protected]
Start with the write sequence
Definition at line 264 of file Controller.cpp.
References msgQueue_, serialport_, and writeComplete().
Referenced by writeCallback(), and writeComplete().
Member Data Documentation
baudrate_
unsigned int oCpt::protocol::Serial::baudrate_ [protected]
Definition at line 546 of file Controller.h.
Referenced by open().
callback_
cb_func oCpt::protocol::Serial::callback_ [protected]
Definition at line 543 of file Controller.h.
Referenced by readComplete(), Serial(), and setReadCallback().
csize_
character_size_t oCpt::protocol::Serial::csize_ [protected]
Definition at line 548 of file Controller.h.
Referenced by open().
device_
std::string oCpt::protocol::Serial::device_ [protected]
Definition at line 545 of file Controller.h.
Referenced by open().
firstMsg
bool oCpt::protocol::Serial::firstMsg = true [protected]
Definition at line 552 of file Controller.h.
flow_
flow_control_t oCpt::protocol::Serial::flow_ [protected]
Definition at line 549 of file Controller.h.
Referenced by open().
ioservice_
io_service_t oCpt::protocol::Serial::ioservice_ [protected]
Definition at line 544 of file Controller.h.
Referenced by close(), open(), setIOservice(), start(), and write().
maxReadLength_
unsigned int oCpt::protocol::Serial::maxReadLength_ [protected]
Definition at line 529 of file Controller.h.
Referenced by ReadStart(), and setMaxReadLength().
msg_
std::string oCpt::protocol::Serial::msg_ [protected]
Definition at line 540 of file Controller.h.
msgQueue_
std::deque<std::vector<unsigned char> > oCpt::protocol::Serial::msgQueue_ [protected]
Definition at line 538 of file Controller.h.
Referenced by writeCallback(), writeComplete(), and writeStart().
msgRecievedSig
signal_t oCpt::protocol::Serial::msgRecievedSig
The signal which is send when a new line has been recieved or the buffer is full
Definition at line 484 of file Controller.h.
Referenced by oCpt::LoRa::initialize(), and internalCallback().
parity_
parity_t oCpt::protocol::Serial::parity_ [protected]
Definition at line 547 of file Controller.h.
Referenced by open().
read_msg
unsigned char oCpt::protocol::Serial::read_msg[4096] [protected]
Definition at line 542 of file Controller.h.
Referenced by readComplete(), and ReadStart().
receivedMsg_
std::string oCpt::protocol::Serial::receivedMsg_ [protected]
Definition at line 541 of file Controller.h.
Referenced by internalCallback().
returnMsgQueue_
std::deque<std::string> oCpt::protocol::Serial::returnMsgQueue_ [protected]
Definition at line 539 of file Controller.h.
Referenced by getReturnMsgQueue(), internalCallback(), and readFiFoMsg().
serialport_
serialport_t oCpt::protocol::Serial::serialport_ [protected]
Definition at line 551 of file Controller.h.
Referenced by close(), closeCallback(), isOpen(), open(), ReadStart(), and writeStart().
stop_
stop_bits_t oCpt::protocol::Serial::stop_ [protected]
Definition at line 550 of file Controller.h.
Referenced by open().
The documentation for this class was generated from the following files:
include/Core/Controller.h
src/Core/Controller.cpp