oCpt::Boatswain Class Reference
#include <Boatswain.h>
Public Member Functions
Boatswain (iController::ptr controller)
virtual ~Boatswain () override
virtual void run () override
virtual void stop () override
virtual void initialize () override
virtual void registerSensor (iSensor::ptr sensor) override
virtual void registerActuator (iActuator::ptr actuator) override
virtual void registerComm (iComm::ptr comm) override
Protected Member Functions
void resetTimer (iSensor::ptr sensor) override
Additional Inherited Members
Detailed Description
The Boatswain performs all the labours tasks, suchs updateing and interpretting sensor readings, setting actuators according to the Captain wishes, updating the state representation of the vessel in the World. Each Boatswain runs on its own thread. It is possible for a vessel to have multiple Boatswains, responsible for multiple tasks, such as communication, localization, steering. Each Boatswain has to adhere to the iBoatswain interface.
Definition at line 113 of file Boatswain.h.
Constructor & Destructor Documentation
Boatswain()
oCpt::Boatswain::Boatswain (iController::ptr controller)
The constructor for a Boatswain
Parameters
controller a shared_ptr to the controller with which teh Boatswain interacts
Definition at line 29 of file Boatswain.cpp.
 Boatswain()
oCpt::Boatswain::~Boatswain () [override], [virtual]
Deconstructor
Definition at line 33 of file Boatswain.cpp.
Member Function Documentation
initialize()
void oCpt::Boatswain::initialize () [override], [virtual]
Initialize the Boatswain
Implements oCpt::iBoatswain.
Definition at line 48 of file Boatswain.cpp.
registerActuator()
void oCpt::Boatswain::registerActuator (iActuator::ptr actuator) [override], [virtual]
Register a new Actuator with the Boatswain
Parameters
actuator a shared_ptr to an Actuator
Implements oCpt::iBoatswain.
Definition at line 71 of file Boatswain.cpp.
registerComm()
void oCpt::Boatswain::registerComm (iComm::ptr comm) [override], [virtual]
Register a new iComm device by setting a shared IO service
Parameters
comm
Implements oCpt::iBoatswain.
Definition at line 100 of file Boatswain.cpp.
References oCpt::iBoatswain::ioservice_.
registerSensor()
void oCpt::Boatswain::registerSensor (iSensor::ptr sensor) [override], [virtual]
Register a new Sensor with the Boatswain. If the Timer for the Sensor is set to a value greater the 0, the Sensor is registered with the timerSensors_ and a timer is set. Otherwise the Sensor is registered as a manualSensors_
Parameters
sensor a shared_ptr to a Sensor
If the timer is set for the sensor, create a new timer service, register the sensor with the timer sensors, and set the callback functions to execute the Sensor::run function and the internall resetTimer function. If the timer is not set register the Sonsor with the manual sensor.
Implements oCpt::iBoatswain.
Definition at line 52 of file Boatswain.cpp.
References oCpt::iBoatswain::ioservice_, oCpt::iBoatswain::manualSensors_, resetTimer(), oCpt::iSensor::run(), oCpt::iBoatswain::timers_, and oCpt::iBoatswain::timerSensors_.
resetTimer()
void oCpt::Boatswain::resetTimer (iSensor::ptr sensor) [override], [protected], [virtual]
reset the timer of a Sensor
Parameters
sensor a shared_ptr to the Sensor
Don't excute if the thread is stopped
Find the current index of the sensor, this could maybe optimized by using a mappping list
Set the new timer. drift isn't taken into account at the current time.
Implements oCpt::iBoatswain.
Definition at line 75 of file Boatswain.cpp.
References oCpt::iBoatswain::ioservice_, oCpt::iBoatswain::localStopThread_, oCpt::iSensor::run(), oCpt::iBoatswain::stopThread_, oCpt::iBoatswain::timers_, and oCpt::iBoatswain::timerSensors_.
Referenced by registerSensor().
run()
void oCpt::Boatswain::run () [override], [virtual]
Make the Boatswain work and execute the actuators, sensors and communications
Implements oCpt::iBoatswain.
Definition at line 37 of file Boatswain.cpp.
References oCpt::iBoatswain::ioservice_, and oCpt::iBoatswain::manualSensors_.
stop()
void oCpt::Boatswain::stop () [override], [virtual]
Stop the execution of the tasks
Implements oCpt::iBoatswain.
Definition at line 44 of file Boatswain.cpp.
References oCpt::iBoatswain::localStopThread_.
The documentation for this class was generated from the following files:
include/Core/Boatswain.h
src/Core/Boatswain.cpp