oCpt::components::sensors::PT100 Class Reference
#include <PT100.h>
Public Types
typedef quantity< celsius::temperature, double > ReturnValue_t
Public Member Functions
PT100 (iController::ptr controller, World::ptr world, std::string id, uint8_t pinid, uint8_t device)
~PT100 ()
void updateSensor ()
void run ()
void stop ()
void init ()
void setCalibrationTemperature (std::pair< ReturnValue_t, ReturnValue_t > temparature, std::pair< uint16_t, uint16_t > analogeValue)
Private Attributes
uint16_t _analogeValue
uint8_t _device = 0
uint8_t _pinid = 0
ReturnValue_t _dy_dx = 1.0 * celsius::degree
ReturnValue_t _constant = 0.0 * celsius::degree
Additional Inherited Members
Detailed Description
A standard PT100 sensors
Definition at line 19 of file PT100.h.
Member Typedef Documentation
ReturnValue_t
typedef quantity<celsius::temperature, double> oCpt::components::sensors::PT100::ReturnValue_t
Definition at line 21 of file PT100.h.
Constructor & Destructor Documentation
PT100()
oCpt::components::sensors::PT100::PT100 (iController::ptr controller, World::ptr world, std::string id, uint8_t pinid, uint8_t device)
Definition at line 12 of file PT100.cpp.
 PT100()
oCpt::components::sensors::PT100::~PT100 ()
Definition at line 19 of file PT100.cpp.
Member Function Documentation
init()
void oCpt::components::sensors::PT100::init () [virtual]
Initialize the sensor
Reimplemented from oCpt::Sensor.
Definition at line 48 of file PT100.cpp.
References oCpt::Sensor::init().
run()
void oCpt::components::sensors::PT100::run () [virtual]
virtual function starting the run service for the IO
Reimplemented from oCpt::Sensor.
Definition at line 39 of file PT100.cpp.
References oCpt::iSensor::sig_, and updateSensor().
setCalibrationTemperature()
void oCpt::components::sensors::PT100::setCalibrationTemperature (std::pair< ReturnValue_t, ReturnValue_t > temparature, std::pair< uint16_t, uint16_t > analogeValue)
Definition at line 31 of file PT100.cpp.
References _constant, and _dy_dx.
stop()
void oCpt::components::sensors::PT100::stop () [virtual]
virtual function stopping the run
Reimplemented from oCpt::Sensor.
Definition at line 44 of file PT100.cpp.
References oCpt::Sensor::stop().
updateSensor()
void oCpt::components::sensors::PT100::updateSensor () [virtual]
virtual function which performs a sensor update, obtaining a new value and sending a signal afterwards
Reimplemented from oCpt::Sensor.
Definition at line 23 of file PT100.cpp.
References _analogeValue, _constant, _dy_dx, _pinid, oCpt::iSensor::controller_, oCpt::iSensor::State::Stamp, oCpt::iSensor::state_, oCpt::iSensor::State::Value, and oCpt::iSensor::world_.
Referenced by run().
Member Data Documentation
_analogeValue
uint16_t oCpt::components::sensors::PT100::_analogeValue [private]
Definition at line 39 of file PT100.h.
Referenced by updateSensor().
_constant
ReturnValue_t oCpt::components::sensors::PT100::_constant = 0.0 * celsius::degree [private]
Definition at line 43 of file PT100.h.
Referenced by setCalibrationTemperature(), and updateSensor().
_device
uint8_t oCpt::components::sensors::PT100::_device = 0 [private]
Definition at line 40 of file PT100.h.
_dy_dx
ReturnValue_t oCpt::components::sensors::PT100::_dy_dx = 1.0 * celsius::degree [private]
Definition at line 42 of file PT100.h.
Referenced by setCalibrationTemperature(), and updateSensor().
_pinid
uint8_t oCpt::components::sensors::PT100::_pinid = 0 [private]
Definition at line 41 of file PT100.h.
Referenced by updateSensor().
The documentation for this class was generated from the following files:
/projects/mti/ohCaptain/ohCaptain/include/Sensors/PT100.h
/projects/mti/ohCaptain/ohCaptain/src/Sensors/PT100.cpp