oCpt::components::sensors::KalmanIMU Class Reference
#include <KalmanIMU.h>
Classes
struct ReturnValue
Public Types
typedef struct oCpt::components::sensors::KalmanIMU::ReturnValue ReturnValue_t
Public Member Functions
KalmanIMU (iController::ptr controller, World::ptr world, std::string id, Razor::ptr RazorSensor)
~KalmanIMU ()
void updateSensor ()
void run ()
void init ()
void setIOservice (boost::shared_ptr< boost::asio::io_service > ioservice)
Private Member Functions
void RazorUpdate ()
Private Attributes
std::string device_
Razor::ptr razor_
Additional Inherited Members
Detailed Description
Definition at line 229 of file KalmanIMU.h.
Member Typedef Documentation
ReturnValue_t
typedef struct oCpt::components::sensors::KalmanIMU::ReturnValue oCpt::components::sensors::KalmanIMU::ReturnValue_t
Constructor & Destructor Documentation
KalmanIMU()
oCpt::components::sensors::KalmanIMU::KalmanIMU (iController::ptr controller, World::ptr world, std::string id, Razor::ptr RazorSensor)
Definition at line 7 of file KalmanIMU.cpp.
References razor_, and RazorUpdate().
 KalmanIMU()
oCpt::components::sensors::KalmanIMU::~KalmanIMU ()
Definition at line 14 of file KalmanIMU.cpp.
Member Function Documentation
init()
void oCpt::components::sensors::KalmanIMU::init () [virtual]
Initialize the sensor
Reimplemented from oCpt::Sensor.
Definition at line 26 of file KalmanIMU.cpp.
References oCpt::Sensor::init().
RazorUpdate()
void oCpt::components::sensors::KalmanIMU::RazorUpdate () [private]
Definition at line 34 of file KalmanIMU.cpp.
References oCpt::components::sensors::Razor::ReturnValue::acc, CAST, and razor_.
Referenced by KalmanIMU().
run()
void oCpt::components::sensors::KalmanIMU::run () [virtual]
virtual function starting the run service for the IO
Reimplemented from oCpt::Sensor.
Definition at line 22 of file KalmanIMU.cpp.
References oCpt::Sensor::run().
setIOservice()
void oCpt::components::sensors::KalmanIMU::setIOservice (boost::shared_ptr< boost::asio::io_service > ioservice) [virtual]
Setting the used Asynchronous Input Output service
Parameters
ioservice ASIO IO service, which handles the async calls from multiple sensors
Reimplemented from oCpt::Sensor.
Definition at line 30 of file KalmanIMU.cpp.
References oCpt::Sensor::setIOservice().
updateSensor()
void oCpt::components::sensors::KalmanIMU::updateSensor () [virtual]
virtual function which performs a sensor update, obtaining a new value and sending a signal afterwards
Reimplemented from oCpt::Sensor.
Definition at line 18 of file KalmanIMU.cpp.
References oCpt::Sensor::updateSensor().
Member Data Documentation
device_
std::string oCpt::components::sensors::KalmanIMU::device_ [private]
Definition at line 252 of file KalmanIMU.h.
razor_
Razor::ptr oCpt::components::sensors::KalmanIMU::razor_ [private]
Definition at line 253 of file KalmanIMU.h.
Referenced by KalmanIMU(), and RazorUpdate().
The documentation for this class was generated from the following files:
/projects/mti/ohCaptain/ohCaptain/include/Sensors/KalmanIMU.h
/projects/mti/ohCaptain/ohCaptain/src/Sensors/KalmanIMU.cpp