oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase > Class Template Reference
#include <KalmanIMU.h>
Public Types
typedef StateKalmanIMU< T > S
typedef PositionMeasurementKalmanIMU< T > M
Public Member Functions
PositionMeasurementModelKalmanIMU ()
M h (const S &x) const
Detailed Description
template<typename T, template< class > class CovarianceBase = Kalman::StandardBase>
class oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase >
Definition at line 207 of file KalmanIMU.h.
Member Typedef Documentation
M
template<typename T , template< class > class CovarianceBase = Kalman::StandardBase>
typedef PositionMeasurementKalmanIMU<T> oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase >::M
Definition at line 212 of file KalmanIMU.h.
S
template<typename T , template< class > class CovarianceBase = Kalman::StandardBase>
typedef StateKalmanIMU<T> oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase >::S
Definition at line 210 of file KalmanIMU.h.
Constructor & Destructor Documentation
PositionMeasurementModelKalmanIMU()
template<typename T , template< class > class CovarianceBase = Kalman::StandardBase>
oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase >::PositionMeasurementModelKalmanIMU () [inline]
Definition at line 214 of file KalmanIMU.h.
Member Function Documentation
h()
template<typename T , template< class > class CovarianceBase = Kalman::StandardBase>
M oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase >::h (const S & x) const [inline]
Definition at line 218 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::acc_x(), oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_x(), oCpt::components::sensors::StateKalmanIMU< T >::acc_y(), oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_y(), oCpt::components::sensors::StateKalmanIMU< T >::acc_z(), and oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_z().
The documentation for this class was generated from the following file:
/projects/mti/ohCaptain/ohCaptain/include/Sensors/KalmanIMU.h