oCpt::components::sensors::Gps Class Reference
#include <Gps.h>
Public Types
typedef oCpt::World::Location::gpsPoint_t ReturnValue_t
Public Member Functions
Gps (iController::ptr controller, World::ptr world, std::string id, std::string device, unsigned int baudrate)
~Gps ()
void updateSensor ()
void run ()
void stop ()
void setIOservice (boost::shared_ptr< boost::asio::io_service > ioservice)
Protected Member Functions
void interpretMsg ()
Protected Attributes
std::string device_
protocol::Serial::ptr serial_
Detailed Description
Definition at line 13 of file Gps.h.
Member Typedef Documentation
ReturnValue_t
typedef oCpt::World::Location::gpsPoint_t oCpt::components::sensors::Gps::ReturnValue_t
Definition at line 15 of file Gps.h.
Constructor & Destructor Documentation
Gps()
oCpt::components::sensors::Gps::Gps (iController::ptr controller, World::ptr world, std::string id, std::string device, unsigned int baudrate)
Definition at line 13 of file Gps.cpp.
References interpretMsg(), and serial_.
 Gps()
oCpt::components::sensors::Gps::~Gps ()
Definition at line 28 of file Gps.cpp.
References serial_.
Member Function Documentation
interpretMsg()
void oCpt::components::sensors::Gps::interpretMsg () [protected]
Definition at line 59 of file Gps.cpp.
References oCpt::World::Location::coordinate::direction, oCpt::World::Location::gpsPoint::latitude, oCpt::World::Location::gpsPoint::longitude, serial_, oCpt::iSensor::sig_, oCpt::iSensor::State::Stamp, oCpt::iSensor::state_, oCpt::World::Location::stocd(), oCpt::iSensor::State::Value, oCpt::World::Location::coordinate::value, and oCpt::iSensor::world_.
Referenced by Gps().
run()
void oCpt::components::sensors::Gps::run () [virtual]
virtual function starting the run service for the IO
Reimplemented from oCpt::Sensor.
Definition at line 38 of file Gps.cpp.
References oCpt::Sensor::run(), oCpt::iSensor::sensorRunning_, and serial_.
setIOservice()
void oCpt::components::sensors::Gps::setIOservice (boost::shared_ptr< boost::asio::io_service > ioservice) [virtual]
Setting the used Asynchronous Input Output service
Parameters
ioservice ASIO IO service, which handles the async calls from multiple sensors
Reimplemented from oCpt::Sensor.
Definition at line 54 of file Gps.cpp.
References serial_, and oCpt::Sensor::setIOservice().
stop()
void oCpt::components::sensors::Gps::stop () [virtual]
virtual function stopping the run
Reimplemented from oCpt::Sensor.
Definition at line 45 of file Gps.cpp.
References oCpt::iSensor::sensorRunning_, serial_, and oCpt::Sensor::stop().
updateSensor()
void oCpt::components::sensors::Gps::updateSensor () [virtual]
virtual function which performs a sensor update, obtaining a new value and sending a signal afterwards
Reimplemented from oCpt::Sensor.
Definition at line 34 of file Gps.cpp.
References oCpt::Sensor::updateSensor().
Member Data Documentation
device_
std::string oCpt::components::sensors::Gps::device_ [protected]
Definition at line 31 of file Gps.h.
serial_
protocol::Serial::ptr oCpt::components::sensors::Gps::serial_ [protected]
Definition at line 32 of file Gps.h.
Referenced by Gps(), interpretMsg(), run(), setIOservice(), stop(), and ~Gps().
The documentation for this class was generated from the following files:
/projects/mti/ohCaptain/ohCaptain/include/Sensors/Gps.h
/projects/mti/ohCaptain/ohCaptain/src/Sensors/Gps.cpp