oCpt::components::sensors::Razor Class Reference
#include <Razor.h>
Classes
struct ReturnValue
Public Types
enum Mode { CONT = 0,
REQ = 1
 }
typedef quantity< si::magnetic_flux_density, float > Magnetic_flux_density_t
typedef quantity< si::angular_velocity, float > Angular_velocity_t
typedef quantity< si::acceleration, float > Acceleration_t
typedef struct oCpt::components::sensors::Razor::ReturnValue ReturnValue_t
Public Member Functions
Razor (iController::ptr controller, World::ptr world, std::string id, std::string device, unsigned int baudrate, Mode mode=Mode::CONT, uint8_t freq=50)
~Razor ()
void updateSensor ()
void run ()
void stop ()
void init ()
void setIOservice (boost::shared_ptr< boost::asio::io_service > ioservice)
Mode getMode () const
void setMode (Mode mode)
uint8_t getFreq () const
void setFreq (uint8_t freq)
Private Member Functions
void fillReturnValue (ReturnValue_t &retVal, float *values)
void msgHandler (const unsigned char *data, size_t size)
bool checkLRC (std::vector< char *> data)
Private Attributes
std::string device_
protocol::Serial::ptr serial_
protocol::Serial::cb_func cb
Mode mode_
uint8_t freq_ = 50
Additional Inherited Members
Detailed Description
Definition at line 15 of file Razor.h.
Member Typedef Documentation
Acceleration_t
typedef quantity<si::acceleration, float> oCpt::components::sensors::Razor::Acceleration_t
Definition at line 19 of file Razor.h.
Angular_velocity_t
typedef quantity<si::angular_velocity, float> oCpt::components::sensors::Razor::Angular_velocity_t
Definition at line 18 of file Razor.h.
Magnetic_flux_density_t
typedef quantity<si::magnetic_flux_density, float> oCpt::components::sensors::Razor::Magnetic_flux_density_t
Definition at line 17 of file Razor.h.
ReturnValue_t
typedef struct oCpt::components::sensors::Razor::ReturnValue oCpt::components::sensors::Razor::ReturnValue_t
Member Enumeration Documentation
Mode
enum oCpt::components::sensors::Razor::Mode
Enumerator
CONT
REQ
Definition at line 27 of file Razor.h.
Constructor & Destructor Documentation
Razor()
oCpt::components::sensors::Razor::Razor (iController::ptr controller, World::ptr world, std::string id, std::string device, unsigned int baudrate, Mode mode = Mode::CONT, uint8_t freq = 50)
Definition at line 13 of file Razor.cpp.
References fillReturnValue(), serial_, oCpt::iSensor::State::Stamp, oCpt::iSensor::state_, oCpt::iSensor::State::Value, and oCpt::iSensor::world_.
 Razor()
oCpt::components::sensors::Razor::~Razor ()
Definition at line 35 of file Razor.cpp.
References serial_.
Member Function Documentation
checkLRC()
bool oCpt::components::sensors::Razor::checkLRC (std::vector< char *> data) [private]
Definition at line 120 of file Razor.cpp.
fillReturnValue()
void oCpt::components::sensors::Razor::fillReturnValue (Razor::ReturnValue_t & retVal, float * values) [private]
Definition at line 85 of file Razor.cpp.
References oCpt::components::sensors::Razor::ReturnValue::acc, oCpt::components::sensors::Razor::ReturnValue::gyro, and oCpt::components::sensors::Razor::ReturnValue::mag.
Referenced by msgHandler(), and Razor().
getFreq()
uint8_t oCpt::components::sensors::Razor::getFreq () const
Definition at line 144 of file Razor.cpp.
References freq_.
getMode()
Razor::Mode oCpt::components::sensors::Razor::getMode () const
Definition at line 131 of file Razor.cpp.
References mode_.
init()
void oCpt::components::sensors::Razor::init () [virtual]
Initialize the sensor
Reimplemented from oCpt::Sensor.
Definition at line 75 of file Razor.cpp.
References cb, freq_, mode_, serial_, setFreq(), and setMode().
msgHandler()
void oCpt::components::sensors::Razor::msgHandler (const unsigned char * data, size_t size) [private]
Definition at line 98 of file Razor.cpp.
References fillReturnValue(), oCpt::iSensor::sig_, oCpt::iSensor::State::Stamp, oCpt::iSensor::state_, oCpt::iSensor::State::Value, and oCpt::iSensor::world_.
run()
void oCpt::components::sensors::Razor::run () [virtual]
virtual function starting the run service for the IO
Reimplemented from oCpt::Sensor.
Definition at line 53 of file Razor.cpp.
References oCpt::Sensor::run(), oCpt::iSensor::sensorRunning_, and serial_.
setFreq()
void oCpt::components::sensors::Razor::setFreq (uint8_t freq)
Definition at line 148 of file Razor.cpp.
References freq_, and serial_.
Referenced by init().
setIOservice()
void oCpt::components::sensors::Razor::setIOservice (boost::shared_ptr< boost::asio::io_service > ioservice) [virtual]
Setting the used Asynchronous Input Output service
Parameters
ioservice ASIO IO service, which handles the async calls from multiple sensors
Reimplemented from oCpt::Sensor.
Definition at line 70 of file Razor.cpp.
References serial_, and oCpt::Sensor::setIOservice().
setMode()
void oCpt::components::sensors::Razor::setMode (Razor::Mode mode)
Definition at line 135 of file Razor.cpp.
References mode_, and serial_.
Referenced by init().
stop()
void oCpt::components::sensors::Razor::stop () [virtual]
virtual function stopping the run
Reimplemented from oCpt::Sensor.
Definition at line 60 of file Razor.cpp.
References oCpt::iSensor::sensorRunning_, serial_, and oCpt::Sensor::stop().
updateSensor()
void oCpt::components::sensors::Razor::updateSensor () [virtual]
virtual function which performs a sensor update, obtaining a new value and sending a signal afterwards
Reimplemented from oCpt::Sensor.
Definition at line 41 of file Razor.cpp.
References mode_, serial_, oCpt::iSensor::State::Stamp, oCpt::iSensor::state_, oCpt::Sensor::updateSensor(), and oCpt::iSensor::world_.
Member Data Documentation
cb
protocol::Serial::cb_func oCpt::components::sensors::Razor::cb [private]
Definition at line 50 of file Razor.h.
Referenced by init().
device_
std::string oCpt::components::sensors::Razor::device_ [private]
Definition at line 48 of file Razor.h.
freq_
uint8_t oCpt::components::sensors::Razor::freq_ = 50 [private]
Definition at line 62 of file Razor.h.
Referenced by getFreq(), init(), and setFreq().
mode_
Mode oCpt::components::sensors::Razor::mode_ [private]
Definition at line 51 of file Razor.h.
Referenced by getMode(), init(), setMode(), and updateSensor().
serial_
protocol::Serial::ptr oCpt::components::sensors::Razor::serial_ [private]
Definition at line 49 of file Razor.h.
Referenced by init(), Razor(), run(), setFreq(), setIOservice(), setMode(), stop(), updateSensor(), and ~Razor().
The documentation for this class was generated from the following files:
/projects/mti/ohCaptain/ohCaptain/include/Sensors/Razor.h
/projects/mti/ohCaptain/ohCaptain/src/Sensors/Razor.cpp