oCpt::Sensor Class Reference
#include <Sensor.h>
Public Member Functions
Sensor (iController::ptr controller, World::ptr world, std::string id, std::string typeOfSensor)
virtual ~Sensor () override
virtual void updateSensor () override
virtual void run () override
virtual void stop () override
virtual void init () override
virtual void setIOservice (boost::shared_ptr< boost::asio::io_service > ioservice) override
Additional Inherited Members
Detailed Description
Implementation of the iSensor interface
Definition at line 152 of file Sensor.h.
Constructor & Destructor Documentation
Sensor()
oCpt::Sensor::Sensor (iController::ptr controller, World::ptr world, std::string id, std::string typeOfSensor)
Constructor of Sensor
Parameters
controller a shared_ptr of the controller where the sensor is hooked to
world a shared_ptr of the world in which the vessel operates
id a identifying name of the sensor
typeOfSensor a identifying category for the sensor
Definition at line 57 of file Sensor.cpp.
 Sensor()
oCpt::Sensor::~Sensor () [override], [virtual]
Deconstructor of the Sensor class
Definition at line 62 of file Sensor.cpp.
Member Function Documentation
init()
void oCpt::Sensor::init () [override], [virtual]
Initialize the sensor
Implements oCpt::iSensor.
Reimplemented in oCpt::components::sensors::KalmanIMU, oCpt::components::sensors::Razor, and oCpt::components::sensors::PT100.
Definition at line 78 of file Sensor.cpp.
Referenced by oCpt::components::sensors::PT100::init(), and oCpt::components::sensors::KalmanIMU::init().
run()
void oCpt::Sensor::run () [override], [virtual]
virtual function starting the run service for the IO
Implements oCpt::iSensor.
Reimplemented in oCpt::components::sensors::KalmanIMU, oCpt::components::sensors::Razor, oCpt::components::sensors::PT100, and oCpt::components::sensors::Gps.
Definition at line 70 of file Sensor.cpp.
References oCpt::iSensor::sensorRunning_.
Referenced by oCpt::components::sensors::Gps::run(), oCpt::components::sensors::Razor::run(), and oCpt::components::sensors::KalmanIMU::run().
setIOservice()
void oCpt::Sensor::setIOservice (boost::shared_ptr< boost::asio::io_service > ioservice) [override], [virtual]
Setting the used Asynchronous Input Output service
Parameters
ioservice ASIO IO service, which handles the async calls from multiple sensors
Implements oCpt::iSensor.
Reimplemented in oCpt::components::sensors::KalmanIMU, oCpt::components::sensors::Razor, and oCpt::components::sensors::Gps.
Definition at line 82 of file Sensor.cpp.
References oCpt::iSensor::ioservice_.
Referenced by oCpt::components::sensors::Gps::setIOservice(), oCpt::components::sensors::Razor::setIOservice(), and oCpt::components::sensors::KalmanIMU::setIOservice().
stop()
void oCpt::Sensor::stop () [override], [virtual]
virtual function stopping the run
Implements oCpt::iSensor.
Reimplemented in oCpt::components::sensors::Razor, oCpt::components::sensors::PT100, and oCpt::components::sensors::Gps.
Definition at line 74 of file Sensor.cpp.
References oCpt::iSensor::sensorRunning_.
Referenced by oCpt::components::sensors::Gps::stop(), oCpt::components::sensors::PT100::stop(), and oCpt::components::sensors::Razor::stop().
updateSensor()
void oCpt::Sensor::updateSensor () [override], [virtual]
virtual function which performs a sensor update, obtaining a new value and sending a signal afterwards
Implements oCpt::iSensor.
Reimplemented in oCpt::components::sensors::KalmanIMU, oCpt::components::sensors::Razor, oCpt::components::sensors::PT100, and oCpt::components::sensors::Gps.
Definition at line 66 of file Sensor.cpp.
Referenced by oCpt::components::sensors::Gps::updateSensor(), oCpt::components::sensors::Razor::updateSensor(), and oCpt::components::sensors::KalmanIMU::updateSensor().
The documentation for this class was generated from the following files:
/projects/mti/ohCaptain/ohCaptain/include/Core/Sensor.h
/projects/mti/ohCaptain/ohCaptain/src/Core/Sensor.cpp