oCpt::components::sensors::OrientationMeasurementKalmanIMU< T > Class Template Reference
#include <KalmanIMU.h>
Public Types
typedef Kalman::Vector< T, 6 > Base
Public Member Functions
OrientationMeasurementKalmanIMU (void)
template<typename OtherDerived >
OrientationMeasurementKalmanIMU (const Eigen::MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
OrientationMeasurementKalmanIMU & operator= (const Eigen::MatrixBase< OtherDerived > &other)
T theta () const
T psi () const
T phi () const
T thetaPrime () const
T psiPrime () const
T phiPrime () const
T & theta ()
T & psi ()
T & phi ()
T & thetaPrime ()
T & psiPrime ()
T & phiPrime ()
Static Public Attributes
static constexpr size_t Theta = 0
static constexpr size_t Psi = 1
static constexpr size_t Phi = 2
static constexpr size_t ThetaPrime = 3
static constexpr size_t PsiPrime = 4
static constexpr size_t PhiPrime = 5
Detailed Description
template<typename T>
class oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >
Definition at line 120 of file KalmanIMU.h.
Member Typedef Documentation
Base
template<typename T >
typedef Kalman::Vector< T , 6 > oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::Base
Definition at line 122 of file KalmanIMU.h.
Constructor & Destructor Documentation
OrientationMeasurementKalmanIMU() [1/2]
template<typename T >
oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::OrientationMeasurementKalmanIMU (void) [inline]
Definition at line 122 of file KalmanIMU.h.
OrientationMeasurementKalmanIMU() [2/2]
template<typename T >
template<typename OtherDerived >
oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::OrientationMeasurementKalmanIMU (const Eigen::MatrixBase< OtherDerived > & other) [inline]
Definition at line 122 of file KalmanIMU.h.
Member Function Documentation
operator=()
template<typename T >
template<typename OtherDerived >
OrientationMeasurementKalmanIMU& oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::operator= (const Eigen::MatrixBase< OtherDerived > & other) [inline]
Definition at line 122 of file KalmanIMU.h.
phi() [1/2]
template<typename T >
T oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::phi () const [inline]
Definition at line 135 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::Phi.
Referenced by oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::h().
phi() [2/2]
template<typename T >
T& oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::phi () [inline]
Definition at line 147 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::Phi.
phiPrime() [1/2]
template<typename T >
T oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::phiPrime () const [inline]
Definition at line 141 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::PhiPrime.
Referenced by oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::h().
phiPrime() [2/2]
template<typename T >
T& oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::phiPrime () [inline]
Definition at line 153 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::PhiPrime.
psi() [1/2]
template<typename T >
T oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::psi () const [inline]
Definition at line 133 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::Psi.
Referenced by oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::h().
psi() [2/2]
template<typename T >
T& oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::psi () [inline]
Definition at line 145 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::Psi.
psiPrime() [1/2]
template<typename T >
T oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::psiPrime () const [inline]
Definition at line 139 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::PsiPrime.
Referenced by oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::h().
psiPrime() [2/2]
template<typename T >
T& oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::psiPrime () [inline]
Definition at line 151 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::PsiPrime.
theta() [1/2]
template<typename T >
T oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::theta () const [inline]
Definition at line 131 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::Theta.
Referenced by oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::h().
theta() [2/2]
template<typename T >
T& oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::theta () [inline]
Definition at line 143 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::Theta.
thetaPrime() [1/2]
template<typename T >
T oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::thetaPrime () const [inline]
Definition at line 137 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::ThetaPrime.
Referenced by oCpt::components::sensors::OrientationMeasurementModelKalmanIMU< T, CovarianceBase >::h().
thetaPrime() [2/2]
template<typename T >
T& oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::thetaPrime () [inline]
Definition at line 149 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::ThetaPrime.
Member Data Documentation
Phi
template<typename T >
constexpr size_t oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::Phi = 2 [static]
Definition at line 126 of file KalmanIMU.h.
PhiPrime
template<typename T >
constexpr size_t oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::PhiPrime = 5 [static]
Definition at line 129 of file KalmanIMU.h.
Psi
template<typename T >
constexpr size_t oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::Psi = 1 [static]
Definition at line 125 of file KalmanIMU.h.
PsiPrime
template<typename T >
constexpr size_t oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::PsiPrime = 4 [static]
Definition at line 128 of file KalmanIMU.h.
Theta
template<typename T >
constexpr size_t oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::Theta = 0 [static]
Definition at line 124 of file KalmanIMU.h.
ThetaPrime
template<typename T >
constexpr size_t oCpt::components::sensors::OrientationMeasurementKalmanIMU< T >::ThetaPrime = 3 [static]
Definition at line 127 of file KalmanIMU.h.
The documentation for this class was generated from the following file:
/projects/mti/ohCaptain/ohCaptain/include/Sensors/KalmanIMU.h