oCpt::protocol::gpio Class Reference
#include <Controller.h>
Public Types
enum Direction { INPUT = 105,
OUTPUT = 111
 }
enum Value { LOW = 48,
HIGH = 49
 }
enum Edge { NONE = 110,
RISING = 114,
FALLING = 102,
BOTH = 98
 }
typedef boost::shared_ptr< gpio > ptr
typedef boost::signals2::signal< void()> signal_t
typedef std::function< void()> cb_func
Public Member Functions
gpio (int pinNumber, Direction direction=INPUT, Value value=LOW, Edge edge=NONE)
~gpio ()
int getPinNumber () const
void setPinNumber (int pinNumber)
Value getValue () const
void setValue (Value value)
Direction getDirection () const
void setDirection (Direction direction)
Edge getEdge () const
void setEdge (Edge edge)
void setCallbackFunction (cb_func cb)
void waitForEdge ()
void waitForEdgeAsync ()
void toggle ()
Static Public Member Functions
static std::vector< ptr > exportedGpios ()
Public Attributes
signal_t signalChanged
Private Member Functions
void internalCbFunc ()
void exportPin (const int &number)
void unexportPin (const int &number)
template<typename T >
void writePinValue (const int &number, const T &value)
template<typename T >
void writePinValue (std::string path, const T &value)
Static Private Member Functions
template<typename T >
static T readPinValue (const int &number)
template<typename T >
static T readPinValue (std::string path)
Private Attributes
int pinNumber_
Value value_
Direction direction_
Edge edge_
std::string gpiopath_
cb_func cb_
bool threadRunning_
Additional Inherited Members
Detailed Description
A General Pin Input Output class. This is the class that handles gpio's in user space. Each pin can be set as either input or output, and have a High or a Low out-/input. When a pin is set as input, it can be polled on the edge, execute a function or send a signal on the rising, falling or changing edge of the signal
Definition at line 138 of file Controller.h.
Member Typedef Documentation
cb_func
typedef std::function<void()> oCpt::protocol::gpio::cb_func
Definition at line 142 of file Controller.h.
ptr
typedef boost::shared_ptr<gpio> oCpt::protocol::gpio::ptr
Definition at line 140 of file Controller.h.
signal_t
typedef boost::signals2::signal<void()> oCpt::protocol::gpio::signal_t
Definition at line 141 of file Controller.h.
Member Enumeration Documentation
Direction
enum oCpt::protocol::gpio::Direction
The Direction of the pin
Enumerator
INPUT
OUTPUT
Definition at line 147 of file Controller.h.
Edge
enum oCpt::protocol::gpio::Edge
Enumerator
NONE
RISING
FALLING
BOTH
Definition at line 157 of file Controller.h.
Value
enum oCpt::protocol::gpio::Value
Enumerator
LOW
HIGH
Definition at line 152 of file Controller.h.
Constructor & Destructor Documentation
gpio()
oCpt::protocol::gpio::gpio (int pinNumber, gpio::Direction direction = INPUT, gpio::Value value = LOW, gpio::Edge edge = NONE)
The constructor for the gpio class
Parameters
pinNumber the pin pumber (in user-space mapping)
direction the Direction of a pin, with a default value as Direction::INPUT
value the start Value of a pin. With a default value of Value::LOW
edge the Edge of a pin with the default value of Edge::NONE
Definition at line 337 of file Controller.cpp.
References cb_, direction_, edge_, exportPin(), GPIO_BASE_PATH, gpiopath_, internalCbFunc(), pinNumber_, and value_.
Referenced by exportedGpios().
 gpio()
oCpt::protocol::gpio::~gpio ()
The deconstructor
Definition at line 353 of file Controller.cpp.
References pinNumber_, and unexportPin().
Member Function Documentation
exportedGpios()
std::vector< gpio::ptr > oCpt::protocol::gpio::exportedGpios () [static]
Static function which creates a vector containing new gpio shared_ptr for each pin that is currently exported in the user space.
Returns
A vector with shared_ptr's of all exported gpio's in user-space
Iterate through all exported pins
Definition at line 357 of file Controller.cpp.
References gpio(), and GPIO_BASE_PATH.
exportPin()
void oCpt::protocol::gpio::exportPin (const int & number) [private]
Export the pin in user-space
Parameters
number the pin number to be exported
Definition at line 381 of file Controller.cpp.
References GPIO_BASE_PATH.
Referenced by gpio().
getDirection()
gpio::Direction oCpt::protocol::gpio::getDirection () const
Get the current Direction. note this doesn't take into accoutn external changes done outside this library
Returns
either Direction::INPUT or Direction::Output
Definition at line 314 of file Controller.cpp.
getEdge()
gpio::Edge oCpt::protocol::gpio::getEdge () const
Get the current Edge of the pin. If the Direction is set to Direction::INPUT the value is set in user-space, otherwise it is set in the object itself
Returns
Definition at line 323 of file Controller.cpp.
getPinNumber()
int oCpt::protocol::gpio::getPinNumber () const
Get the current pin number
Returns
an int representing the pin number in user-space mapping
Definition at line 291 of file Controller.cpp.
getValue()
gpio::Value oCpt::protocol::gpio::getValue () const
Get the current value of the pin, if the Direction is set to Direction::INPUT the value is obtained from the user space, otherwise the value is read from object itself
Returns
either Value::HIGH or Value::LOW
Definition at line 300 of file Controller.cpp.
internalCbFunc()
void oCpt::protocol::gpio::internalCbFunc () [private]
The internal callback function, which triggers the signalChanged signal
Definition at line 418 of file Controller.cpp.
References signalChanged.
Referenced by gpio().
readPinValue() [1/2]
template<typename T >
static T oCpt::protocol::gpio::readPinValue (const int & number) [inline], [static], [private]
Static generic function returning the value in user-space of either Direction, Edge or Value. Depending on the typename
Template Parameters
T The value to return either the Value, Edge or Direction
Parameters
number the pin as number
Returns
The read value as either Value, Edge or Direction
Definition at line 291 of file Controller.h.
References GPIO_BASE_PATH.
readPinValue() [2/2]
template<typename T >
static T oCpt::protocol::gpio::readPinValue (std::string path) [inline], [static], [private]
Static generic function returning the value in user-space of either Direction, Edge or Value. Depending on the typename. This function is quicker then the overload function taking the pin number as int. and is therefore preffered to obtain the Value.
Template Parameters
T The value to return either the Value, Edge or Direction
Parameters
path the pin as user-space path
Returns
the read value as either Value, Edge or Direction
Definition at line 304 of file Controller.h.
References boost::units::constants::c.
setCallbackFunction()
void oCpt::protocol::gpio::setCallbackFunction (gpio::cb_func cb)
Set a new Callbackfunction which is called on a certain Edge
Parameters
cb the callback function
Definition at line 414 of file Controller.cpp.
References cb_.
setDirection()
void oCpt::protocol::gpio::setDirection (gpio::Direction direction)
Set the Direction of the pin
Parameters
direction the Direction of the pin
Definition at line 318 of file Controller.cpp.
References direction_.
setEdge()
void oCpt::protocol::gpio::setEdge (gpio::Edge edge)
Set the Edge of the of the pin. if the Direction is set to Direction::INPUT, the value is set in user-space, otherwise it is set in the object itself
Parameters
edge
Definition at line 330 of file Controller.cpp.
References edge_.
setPinNumber()
void oCpt::protocol::gpio::setPinNumber (int pinNumber)
Set the new pinbumber (don't use yet)
Parameters
pinNumber the pinmuber to be set
Definition at line 295 of file Controller.cpp.
References pinNumber_.
setValue()
void oCpt::protocol::gpio::setValue (gpio::Value value)
Set the current value, if the Direction is set to Direction::OUTPUT the value is set ti userspace, either it is set to object itself
Parameters
value
Definition at line 307 of file Controller.cpp.
References value_.
toggle()
void oCpt::protocol::gpio::toggle ()
Toggle the value_ of the pin if Value::High then the value_ is set to Value::LOW
Definition at line 409 of file Controller.cpp.
References gpiopath_, and value_.
unexportPin()
void oCpt::protocol::gpio::unexportPin (const int & number) [private]
Unexport the pin in user-space
Parameters
number the pin number to be unexported
Definition at line 395 of file Controller.cpp.
References GPIO_BASE_PATH.
Referenced by ~gpio().
waitForEdge()
void oCpt::protocol::gpio::waitForEdge ()
Wait for the occurance of a change in Edge, corresponding with the set value of Edge. When the change is detected the callbackfunction is called. This function blocks the current thread.
Definition at line 422 of file Controller.cpp.
References cb_, direction_, and gpiopath_.
Referenced by waitForEdgeAsync().
waitForEdgeAsync()
void oCpt::protocol::gpio::waitForEdgeAsync ()
Wait for the ocurrance of a change in Edge, corresponding with the set value of Edge. When the chance is detected the callbackfunction is called. This function creates a new thread, allowing the current thread to run unhindered
Definition at line 457 of file Controller.cpp.
References waitForEdge().
writePinValue() [1/2]
template<typename T >
void oCpt::protocol::gpio::writePinValue (const int & number, const T & value) [inline], [private]
Write the value to the pin. The T parameter determines which value to set
Template Parameters
T the type could either be Value, Direction ro Direction
Parameters
number the pin number as an integer
value the Value to be set
Definition at line 331 of file Controller.h.
References GPIO_BASE_PATH.
writePinValue() [2/2]
template<typename T >
void oCpt::protocol::gpio::writePinValue (std::string path, const T & value) [inline], [private]
Write the value to the pin, The T paramter determines which value to set. This overload is quicker then the one taking the integer and is therefore preferred
Template Parameters
T the type could either be Value, Direction or Edge
Parameters
path the pin as an user-space path
value the Value to write
Definition at line 344 of file Controller.h.
Member Data Documentation
cb_
cb_func oCpt::protocol::gpio::cb_ [private]
Definition at line 264 of file Controller.h.
Referenced by gpio(), setCallbackFunction(), and waitForEdge().
direction_
Direction oCpt::protocol::gpio::direction_ [private]
Definition at line 261 of file Controller.h.
Referenced by gpio(), setDirection(), and waitForEdge().
edge_
Edge oCpt::protocol::gpio::edge_ [private]
Definition at line 262 of file Controller.h.
Referenced by gpio(), and setEdge().
gpiopath_
std::string oCpt::protocol::gpio::gpiopath_ [private]
Definition at line 263 of file Controller.h.
Referenced by gpio(), toggle(), and waitForEdge().
pinNumber_
int oCpt::protocol::gpio::pinNumber_ [private]
Definition at line 259 of file Controller.h.
Referenced by gpio(), setPinNumber(), and ~gpio().
signalChanged
signal_t oCpt::protocol::gpio::signalChanged
The signal that is send if the internal callback fucntion is executed
Definition at line 256 of file Controller.h.
Referenced by internalCbFunc().
threadRunning_
bool oCpt::protocol::gpio::threadRunning_ [private]
Definition at line 265 of file Controller.h.
value_
Value oCpt::protocol::gpio::value_ [private]
Definition at line 260 of file Controller.h.
Referenced by gpio(), setValue(), and toggle().
The documentation for this class was generated from the following files:
/projects/mti/ohCaptain/ohCaptain/include/Core/Controller.h
/projects/mti/ohCaptain/ohCaptain/src/Core/Controller.cpp