oCpt::LoRa Class Reference
#include <Communication.h>
Public Types
enum ModulationMode { LORA = 1,
FSK = 2
 }
enum SpreadingFactor {
SF7 = 7,
SF8 = 8,
SF9 = 9,
SF10 = 10,
SF11 = 11,
SF12 = 12
 }
enum BandWidth {
BW250 = 1,
BW200 = 2,
BW166_7 = 3,
BW125 = 4,
BW100 = 5,
BW83_3 = 6,
BW62_5 = 7,
BW50 = 8,
BW41_7 = 9,
BW31_3 = 10,
BW25 = 11,
BW20_8 = 12,
BW15_6 = 13,
BW12_5 = 14,
BW10_4 = 15,
BW7_8 = 16,
BW6_3 = 17,
BW5_2 = 18,
BW3_9 = 19,
BW3_1 = 20,
BW2_6 = 21
 }
enum CodingRate { CR4_5 = 4,
CR4_6 = 3,
CR4_7 = 2,
CR4_8 = 1
 }
enum RadioBandWidth { RBW500 = 500,
RBW250 = 250,
RBW125 = 125
 }
enum GetSet { GET,
SET,
NONE
 }
enum RadioCommand {
MOD,
FREQ,
PWR,
SF,
AFCBW,
RXBW,
FSKBITRATE,
FDEV,
PRLEN,
CRC,
CR,
WDT,
SYNC,
BW,
rRX,
rTX
 }
enum MacCommand {
PAUSE,
RESET,
mTX,
JOIN,
SAVE,
FORCEENABLE,
RESUME
 }
Public Member Functions
LoRa (const std::string &id, const std::string &device, World::ptr world=World::ptr(new World()), iController::io_t ioservice=iController::io_t(new boost::asio::io_service()))
virtual ~LoRa ()
virtual void run () override
virtual void stop () override
virtual void initialize () override
virtual void sendMessage (Message msg) override
virtual Message::ptr recieveMessage () override
virtual void recieveAsyncMessage () override
Protected Member Functions
void messageRecieved ()
std::string bandWidthToString (const BandWidth &value)
std::string codingRateToString (const CodingRate &value)
void stringToHex (const std::string str, std::string &hexStr, const bool capital=true)
void hexToString (const std::string hexStr, std::string &str)
template<typename T >
std::string encodeTypeToHex (T value, bool capital=true)
template<typename T >
std::string buildMacCmdString (MacCommand cmd, T value=0, GetSet prop=NONE)
template<typename T >
std::string buildRadioCmdString (RadioCommand cmd, T value=0, GetSet prop=SET)
std::string buildRadioCmdString (RadioCommand cmd, std::string value, GetSet prop=SET)
unsigned long calculateDownTime (unsigned int payload)
void write (const std::string &value)
void rx ()
void macpause ()
Protected Attributes
bool proceed_
bool ignoreWarn_
bool listen_
protocol::Serial serial_
SerialPort for UART communication with the chip.
unsigned int baudrate_
ModulationMode mod_
Modulation mode.
unsigned long freq_
Frequency between 433050000..4347900000 or 863000000...870000000.
int8_t pwr_
Power of transmission between -3...15.
SpreadingFactor sf_
Spreading factor of the signal.
BandWidth afcbw_
Automatic frequency correction in kHz.
BandWidth rxbw_
Signal bandwidth in kHz.
uint fskBitRate_
FSK bitrate between 1...300000.
uint fdev_
Frequency deviation between 0...200000.
uint prlen_
Preamble length between 0...65535.
bool crc_
CRC Header on or off.
CodingRate cr_
The coding rate.
unsigned long wdt_
WatchDog 0...4294967295. Set to 0 to disable.
unsigned int sync_
Sync word.
RadioBandWidth bw_
RadioBandWidth in kHz.
bool sendAllowed_
Additional Inherited Members
Detailed Description
Communication class for the LoRa protocol. The current class is mostly based on node 2 node communication TODO rewrite sho it will allow mesh network communication. Most of the commands are taken from http://ww1.microchip.com/downloads/en/DeviceDoc/40001784B.pdf
Definition at line 160 of file Communication.h.
Member Enumeration Documentation
BandWidth
enum oCpt::LoRa::BandWidth
The bandwidth
Enumerator
BW250
BW200
BW166_7
BW125
BW100
BW83_3
BW62_5
BW50
BW41_7
BW31_3
BW25
BW20_8
BW15_6
BW12_5
BW10_4
BW7_8
BW6_3
BW5_2
BW3_9
BW3_1
BW2_6
Definition at line 186 of file Communication.h.
CodingRate
enum oCpt::LoRa::CodingRate
The Coding rate of the signal
Enumerator
CR4_5
CR4_6
CR4_7
CR4_8
Definition at line 213 of file Communication.h.
GetSet
enum oCpt::LoRa::GetSet
Perform a get or a set command or otherwise none
Enumerator
GET
SET
NONE
Definition at line 232 of file Communication.h.
MacCommand
enum oCpt::LoRa::MacCommand
Type to control the MAC layer, currently only pause is used, because node 2 node communication doesn't use MAC
Enumerator
PAUSE
RESET
mTX
JOIN
SAVE
FORCEENABLE
RESUME
Definition at line 263 of file Communication.h.
ModulationMode
enum oCpt::LoRa::ModulationMode
The modulation mode of the LoRa module
Enumerator
LORA
FSK
Definition at line 166 of file Communication.h.
RadioBandWidth
enum oCpt::LoRa::RadioBandWidth
The radio bandwidth
Enumerator
RBW500
RBW250
RBW125
Definition at line 223 of file Communication.h.
RadioCommand
enum oCpt::LoRa::RadioCommand
Types of radio commands
Enumerator
MOD
FREQ
PWR
SF
AFCBW
RXBW
FSKBITRATE
FDEV
PRLEN
CRC
CR
WDT
SYNC
BW
rRX
rTX
Definition at line 241 of file Communication.h.
SpreadingFactor
enum oCpt::LoRa::SpreadingFactor
The Spreading factor
Enumerator
SF7
SF8
SF9
SF10
SF11
SF12
Definition at line 174 of file Communication.h.
Constructor & Destructor Documentation
LoRa()
oCpt::LoRa::LoRa (const std::string & id, const std::string & device, World::ptr world = World::ptr(new World()), iController::io_t ioservice = iController::io_t(new boost::asio::io_service()))
LoRa device constructor
Parameters
id the ID of the device as an string
device the device path eq. /dev/ttyS0
world shared_ptr to the World default = a newly created World
ioservice shared_ptr to an IO service, default is a newly created IO service
Definition at line 58 of file Communication.cpp.
 LoRa()
oCpt::LoRa::~LoRa () [virtual]
Definition at line 81 of file Communication.cpp.
Member Function Documentation
bandWidthToString()
std::string oCpt::LoRa::bandWidthToString (const BandWidth & value) [protected]
Definition at line 101 of file Communication.cpp.
References BW100, BW10_4, BW125, BW12_5, BW15_6, BW166_7, BW200, BW20_8, BW25, BW250, BW31_3, BW3_1, BW3_9, BW41_7, BW50, BW5_2, BW62_5, BW6_3, BW7_8, and BW83_3.
buildMacCmdString()
template<typename T >
std::string oCpt::LoRa::buildMacCmdString (MacCommand cmd, T value = 0, GetSet prop = NONE) [inline], [protected]
A command string builder for MAC commands currently onlu PAUSE implemented
Template Parameters
T the type of MAC command eq. MacCommand::PAUSE
Parameters
cmd the MacCommand to be performed
value the Value to be send
prop Additional properties
Returns
a string which can be send to the LoRa module eq. `mac set pause`
Definition at line 339 of file Communication.h.
buildRadioCmdString() [1/2]
template<typename T >
std::string oCpt::LoRa::buildRadioCmdString (RadioCommand cmd, T value = 0, GetSet prop = SET) [inline], [protected]
A command string builder for radio commands
Template Parameters
T
Parameters
cmd
value
prop
Returns
Definition at line 367 of file Communication.h.
Referenced by sendMessage().
buildRadioCmdString() [2/2]
std::string oCpt::LoRa::buildRadioCmdString (RadioCommand cmd, std::string value, GetSet prop = SET) [inline], [protected]
Definition at line 437 of file Communication.h.
calculateDownTime()
unsigned long oCpt::LoRa::calculateDownTime (unsigned int payload) [protected]
Definition at line 85 of file Communication.cpp.
References bw_, cr_, crc_, prlen_, and sf_.
codingRateToString()
std::string oCpt::LoRa::codingRateToString (const CodingRate & value) [protected]
Definition at line 148 of file Communication.cpp.
References CR4_5, CR4_6, and CR4_7.
encodeTypeToHex()
template<typename T >
std::string oCpt::LoRa::encodeTypeToHex (T value, bool capital = true) [inline], [protected]
Convert the value of a Type T to a hexidecimal string, which can be send to a LoRa device, such that it can be transmitted
Template Parameters
T the type of value, to be converted
Parameters
value the to be converted value
capital boolean indicating if the hexidecimal string should consist of capital letters
Returns
a string with the value as hexidecimal values
Definition at line 316 of file Communication.h.
References boost::units::constants::c.
hexToString()
void oCpt::LoRa::hexToString (const std::string hexStr, std::string & str) [protected]
Definition at line 280 of file Communication.cpp.
Referenced by messageRecieved().
initialize()
void oCpt::LoRa::initialize () [override], [virtual]
A pure virtual function which initializes the communication device
Implements oCpt::iComm.
Definition at line 189 of file Communication.cpp.
References AFCBW, afcbw_, BW, bw_, CR, cr_, CRC, crc_, FDEV, fdev_, FREQ, freq_, ignoreWarn_, listen_, macpause(), messageRecieved(), MOD, mod_, oCpt::protocol::Serial::msgRecievedSig, oCpt::protocol::Serial::open(), PRLEN, prlen_, PWR, pwr_, rx(), RXBW, rxbw_, serial_, SF, sf_, oCpt::protocol::Serial::start(), SYNC, sync_, WDT, wdt_, and write().
macpause()
void oCpt::LoRa::macpause () [protected]
Definition at line 275 of file Communication.cpp.
References PAUSE, serial_, and oCpt::protocol::Serial::write().
Referenced by initialize().
messageRecieved()
void oCpt::LoRa::messageRecieved () [protected]
Definition at line 161 of file Communication.cpp.
References hexToString(), ignoreWarn_, listen_, oCpt::iComm::msgQueue_, oCpt::iComm::msgRecievedSig, proceed_, oCpt::protocol::Serial::readFiFoMsg(), rx(), serial_, and oCpt::iComm::world_.
Referenced by initialize().
recieveAsyncMessage()
void oCpt::LoRa::recieveAsyncMessage () [override], [virtual]
A pure virtual function which performs the polling for a new message on a seperate threads, so it won't block the current one, it needs to send a signal when the message is received
Implements oCpt::iComm.
Definition at line 241 of file Communication.cpp.
recieveMessage()
iComm::Message::ptr oCpt::LoRa::recieveMessage () [override], [virtual]
A pure virtual function with a shared_ptr to the first in queue received message, this function will hold the current thread
Returns
a shared_ptr pointing towards the queued Message
Implements oCpt::iComm.
Definition at line 237 of file Communication.cpp.
run()
void oCpt::LoRa::run () [override], [virtual]
a pure virtual function which runs the communication device
Implements oCpt::iComm.
Definition at line 181 of file Communication.cpp.
rx()
void oCpt::LoRa::rx () [protected]
Definition at line 270 of file Communication.cpp.
References NONE, rRX, serial_, and oCpt::protocol::Serial::write().
Referenced by initialize(), messageRecieved(), and sendMessage().
sendMessage()
void oCpt::LoRa::sendMessage (Message msg) [override], [virtual]
A pure virtual function which sends the message
Parameters
msg the Message, consisting of a payload and a time stamp
Implements oCpt::iComm.
Definition at line 222 of file Communication.cpp.
References buildRadioCmdString(), NONE, PAUSE, oCpt::iComm::Message::Payload, rTX, rx(), sendAllowed_, serial_, oCpt::iComm::Message::Stamp, oCpt::iComm::world_, and oCpt::protocol::Serial::write().
stop()
void oCpt::LoRa::stop () [override], [virtual]
A pure virtual function which stops the communication device
Implements oCpt::iComm.
Definition at line 185 of file Communication.cpp.
stringToHex()
void oCpt::LoRa::stringToHex (const std::string str, std::string & hexStr, const bool capital = true) [protected]
Definition at line 245 of file Communication.cpp.
References boost::units::constants::c.
write()
void oCpt::LoRa::write (const std::string & value) [protected]
Definition at line 262 of file Communication.cpp.
References proceed_, serial_, and oCpt::protocol::Serial::write().
Referenced by initialize().
Member Data Documentation
afcbw_
BandWidth oCpt::LoRa::afcbw_ [protected]
Automatic frequency correction in kHz.
Definition at line 470 of file Communication.h.
Referenced by initialize().
baudrate_
unsigned int oCpt::LoRa::baudrate_ [protected]
Definition at line 465 of file Communication.h.
bw_
RadioBandWidth oCpt::LoRa::bw_ [protected]
RadioBandWidth in kHz.
Definition at line 479 of file Communication.h.
Referenced by calculateDownTime(), and initialize().
cr_
CodingRate oCpt::LoRa::cr_ [protected]
The coding rate.
Definition at line 476 of file Communication.h.
Referenced by calculateDownTime(), and initialize().
crc_
bool oCpt::LoRa::crc_ [protected]
CRC Header on or off.
Definition at line 475 of file Communication.h.
Referenced by calculateDownTime(), and initialize().
fdev_
uint oCpt::LoRa::fdev_ [protected]
Frequency deviation between 0...200000.
Definition at line 473 of file Communication.h.
Referenced by initialize().
freq_
unsigned long oCpt::LoRa::freq_ [protected]
Frequency between 433050000..4347900000 or 863000000...870000000.
Definition at line 467 of file Communication.h.
Referenced by initialize().
fskBitRate_
uint oCpt::LoRa::fskBitRate_ [protected]
FSK bitrate between 1...300000.
Definition at line 472 of file Communication.h.
ignoreWarn_
bool oCpt::LoRa::ignoreWarn_ [protected]
Definition at line 462 of file Communication.h.
Referenced by initialize(), and messageRecieved().
listen_
bool oCpt::LoRa::listen_ [protected]
Definition at line 463 of file Communication.h.
Referenced by initialize(), and messageRecieved().
mod_
ModulationMode oCpt::LoRa::mod_ [protected]
Modulation mode.
Definition at line 466 of file Communication.h.
Referenced by initialize().
prlen_
uint oCpt::LoRa::prlen_ [protected]
Preamble length between 0...65535.
Definition at line 474 of file Communication.h.
Referenced by calculateDownTime(), and initialize().
proceed_
bool oCpt::LoRa::proceed_ [protected]
Definition at line 461 of file Communication.h.
Referenced by messageRecieved(), and write().
pwr_
int8_t oCpt::LoRa::pwr_ [protected]
Power of transmission between -3...15.
Definition at line 468 of file Communication.h.
Referenced by initialize().
rxbw_
BandWidth oCpt::LoRa::rxbw_ [protected]
Signal bandwidth in kHz.
Definition at line 471 of file Communication.h.
Referenced by initialize().
sendAllowed_
bool oCpt::LoRa::sendAllowed_ [protected]
Definition at line 480 of file Communication.h.
Referenced by sendMessage().
serial_
protocol::Serial oCpt::LoRa::serial_ [protected]
SerialPort for UART communication with the chip.
Definition at line 464 of file Communication.h.
Referenced by initialize(), macpause(), messageRecieved(), rx(), sendMessage(), and write().
sf_
SpreadingFactor oCpt::LoRa::sf_ [protected]
Spreading factor of the signal.
Definition at line 469 of file Communication.h.
Referenced by calculateDownTime(), and initialize().
sync_
unsigned int oCpt::LoRa::sync_ [protected]
Sync word.
Definition at line 478 of file Communication.h.
Referenced by initialize().
wdt_
unsigned long oCpt::LoRa::wdt_ [protected]
WatchDog 0...4294967295. Set to 0 to disable.
Definition at line 477 of file Communication.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
/projects/mti/ohCaptain/ohCaptain/include/Core/Communication.h
/projects/mti/ohCaptain/ohCaptain/src/Core/Communication.cpp