oCpt::components::sensors::PositionMeasurementKalmanIMU< T > Class Template Reference
#include <KalmanIMU.h>
Public Types
typedef Kalman::Vector< T, 3 > Base
Public Member Functions
PositionMeasurementKalmanIMU (void)
template<typename OtherDerived >
PositionMeasurementKalmanIMU (const Eigen::MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
PositionMeasurementKalmanIMU & operator= (const Eigen::MatrixBase< OtherDerived > &other)
T acc_x () const
T acc_y () const
T acc_z () const
T & acc_x ()
T & acc_y ()
T & acc_z ()
Static Public Attributes
static constexpr size_t accX = 0
static constexpr size_t accY = 1
static constexpr size_t accZ = 2
Detailed Description
template<typename T>
class oCpt::components::sensors::PositionMeasurementKalmanIMU< T >
Definition at line 185 of file KalmanIMU.h.
Member Typedef Documentation
Base
template<typename T>
typedef Kalman::Vector< T , 3 > oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::Base
Definition at line 187 of file KalmanIMU.h.
Constructor & Destructor Documentation
PositionMeasurementKalmanIMU() [1/2]
template<typename T>
oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::PositionMeasurementKalmanIMU (void) [inline]
Definition at line 187 of file KalmanIMU.h.
PositionMeasurementKalmanIMU() [2/2]
template<typename T>
template<typename OtherDerived >
oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::PositionMeasurementKalmanIMU (const Eigen::MatrixBase< OtherDerived > & other) [inline]
Definition at line 187 of file KalmanIMU.h.
Member Function Documentation
acc_x() [1/2]
template<typename T>
T oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_x () const [inline]
Definition at line 193 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::accX.
Referenced by oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase >::h().
acc_x() [2/2]
template<typename T>
T& oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_x () [inline]
Definition at line 199 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::accX.
acc_y() [1/2]
template<typename T>
T oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_y () const [inline]
Definition at line 195 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::accY.
Referenced by oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase >::h().
acc_y() [2/2]
template<typename T>
T& oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_y () [inline]
Definition at line 201 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::accY.
acc_z() [1/2]
template<typename T>
T oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_z () const [inline]
Definition at line 197 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::accZ.
Referenced by oCpt::components::sensors::PositionMeasurementModelKalmanIMU< T, CovarianceBase >::h().
acc_z() [2/2]
template<typename T>
T& oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::acc_z () [inline]
Definition at line 203 of file KalmanIMU.h.
References oCpt::components::sensors::StateKalmanIMU< T >::accZ.
operator=()
template<typename T>
template<typename OtherDerived >
PositionMeasurementKalmanIMU& oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::operator= (const Eigen::MatrixBase< OtherDerived > & other) [inline]
Definition at line 187 of file KalmanIMU.h.
Member Data Documentation
accX
template<typename T>
constexpr size_t oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::accX = 0 [static]
Definition at line 189 of file KalmanIMU.h.
accY
template<typename T>
constexpr size_t oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::accY = 1 [static]
Definition at line 190 of file KalmanIMU.h.
accZ
template<typename T>
constexpr size_t oCpt::components::sensors::PositionMeasurementKalmanIMU< T >::accZ = 2 [static]
Definition at line 191 of file KalmanIMU.h.
The documentation for this class was generated from the following file:
/projects/mti/ohCaptain/ohCaptain/include/Sensors/KalmanIMU.h